name: Manual Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Type of release (patch, minor, major)'
        required: true
        default: 'patch'
      summary:
        description: 'Summary of the changes'
        required: true

permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Create Changeset
        run: |
          mkdir -p .changeset
          cat > .changeset/manual-release.md <<EOF
          ---
          "auth0-tenant-to-tenant-user-migration-tool": ${{ github.event.inputs.releaseType }}
          ---

          ${{ github.event.inputs.summary }}
          EOF

      - name: Run Changeset version
        run: npx changeset version

      - name: Commit version bump
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "chore: version bump via manual release"
          git push

      - name: Build project
        run: npm run build

      - name: Fix package.json issues
        run: npm pkg fix

      - name: Check if version already exists on npm
        run: |
          VERSION=$(node -p "require('./package.json').version")
          EXISTS=$(npm view auth0-tenant-to-tenant-user-migration-tool versions | grep $VERSION || true)
          if [ ! -z "$EXISTS" ]; then
            echo "Version $VERSION already exists on npm. Skipping publish."
            exit 1
          fi

      - name: Tag release
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          npx changeset tag
          git push --follow-tags

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
