name: Version and Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  version-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Check for code changes
        id: changes
        run: |
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          echo "Changed files: $CHANGED_FILES"
          if echo "$CHANGED_FILES" | grep -E '\.(js|ts|json|mjs|cjs|jsx|tsx)$'; then
            echo "Code changes detected."
            echo "run_versioning=true" >> $GITHUB_ENV
          else
            echo "No code changes detected."
            echo "run_versioning=false" >> $GITHUB_ENV

      - name: Bump version and generate changelog
        if: env.run_versioning == 'true'
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          npm run release
          git push --follow-tags origin main

      - name: Build project
        if: env.run_versioning == 'true'
        run: npm run build

      - name: Publish to npm
        if: env.run_versioning == 'true'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
